# Site settings
permalink: /:categories/:year/:month/:day/:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "License.md", "Gemfile", "Gemfile.lock"]
#future: true
future: false

highlighter: rouge

title : HtLtC - An Introduction to R
authors :
  paul:
    name : Paul L. Maurizio 
    github : mauriziopaul
    twitter : TweetNTD
    feedburner : nil
  # email : paul.maurizio@gmail.com
  katrina:
    name : Katrina Kutchko
    github : kutchko
    twitter : kutchko
description : Teaching resources for How to Learn to Code (UNC-Chapel Hill, Summer 2016)
production_url : https://mauriziopaul.github.io/intro-to-R
baseurl : "/intro-to-R" # the subpath
url : "http://mauriziopaul.github.io" # the base hostname & protocol
twitter_username : TweetNTD
github_username :  mauriziopaul
github_username :  kutchko

# Build settings
markdown : kramdown
kramdown :
    input : GFM
