# Site settings
highlighter: rouge

title : Simple Blog (mauriziopaul)
author :
  name : Paul L. Maurizio 
  github : mauriziopaul
  twitter : TweetNTD
  feedburner : nil
# email : paul.maurizio@gmail.com
description : Statistical modeling, and genetics of host-pathogen interactions
production_url : https://mauriziopaul.github.io/blog
baseurl : "/blog" # the subpath of your site, e.g. /blog
url : "http://mauriziopaul.github.io" # the base hostname & protocol for your site
twitter_username : TweetNTD
github_username :  mauriziopaul

# Build settings
markdown : kramdown
kramdown :
    input : GFM
